import type { Metadata } from "next";


export const metadata: Metadata = {
   title: "Mélanie Bruzac - Développeuse Front-end",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        {children}
      </body>
    </html>
  );
}
